scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: ['51.250.27.159:9090']

  - job_name: node-exporter
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: ['51.250.27.159:9100']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://skillfactory.ru
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 51.250.27.159:9115
